 const  swap = {
    numerator: [ 985793558, 1 ],
    denominator: [ 1 ],
    currency: {
      chainId: 1,
      decimals: 18,
      symbol: undefined,
      name: undefined,
      isNative: false,
      isToken: true,
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      buyFeeBps: undefined,
      sellFeeBps: undefined,
      equals: [Function: equals],
      sortsBefore: [Function: sortsBefore],
      wrapped: [Getter]
    },
    decimalScale: [ 660865024, 931322574 ],
    add: [Function: add],
    subtract: [Function: subtract],
    multiply: [Function: multiply],
    divide: [Function: divide],
    toSignificant: [Function: toSignificant],
    toFixed: [Function: toFixed],
    toExact: [Function: toExact],
    wrapped: [Getter],
    invert: [Function: invert],
    lessThan: [Function: lessThan],
    equalTo: [Function: equalTo],
    greaterThan: [Function: greaterThan],
    quotient: [Getter],
    remainder: [Getter],
    asFraction: [Getter]
  }

